### PR TITLE
Form validation

### PR DESCRIPTION
**Pull request by FevenSeyfu**
Milestones,

- Added client-side validation to email
- check if the email is in lowercase
- show error message if not lowercase

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Feven, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your ReadMe for this project complies to the following standards:
- [ ] _Getting Started_ section is missing. All main headers from the [ReadMe template](https://github.com/microverseinc/readme-template) should be present in your ReadMe, only the FAQ section is optional.
- [ ] Kindly ensure that provided text instructions is removed and filled in with custom content applicable to your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Gopxfs** [comment]
# STATUS: INVALID REQUEST

Hi @FevenSeyfu 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project with a README that isn't filled with your data. Please make sure to add:
### 1. Author section (with your corresponding social links e.g. GitHub, LinkedIn...)
### 2. Getting Started section (instructions about how to run your code locally)

Your Code Review Request will be marked invalid in your Dashboard, so please submit a new one once ready 🙏.
Invalid requests don't count as a review, so don't worry about that 😄!

Cheers and Happy coding!👏👏👏

--------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by FevenSeyfu** [comment]
Hi  @Gopxfs
Thank you for your feedback I have added the "Getting started" section with clear instructions and I have also fixed the issue with the Authors section by adding a correct handle to my social links.

**Review by AmaduKamara — APPROVED** [review]
# Status: Approved 🟢 🟢 🟢

Hi @FevenSeyfu,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used the right Gitflow 👍🏽 
✅ Linter checks passed 👍🏽
✅ Form email validation works as expected 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
